services:
  php:
    build: .
    ports:
      - "${PHP_PORT}:9000"
    volumes:
      - .:/var/www/html
    depends_on:
      - db_test
    environment:
      - DATABASE_URL=mysql://root:root@db_test:3306/test
    profiles:
      - default
      - test

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./docker/mysql/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - "${MYSQL_PORT}:3306"
    profiles:
      - default

  db_test:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./docker/mysql/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - "3307:3306"
    profiles:
      - test

  manticore:
    image: manticoresearch/manticore
    ports:
      - "${MANTICORE_PORT}:9306"
      - "9308:9308"
    volumes:
      - ./manticore.conf:/etc/manticoresearch/manticore.conf
      - ./manticore_data:/var/lib/manticore
    profiles:
      - default
      - test

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"        # Порт, на котором будет доступен phpMyAdmin на вашем хосте
    environment:
      PMA_HOST: db_test       # Имя сервиса базы данных (MySQL)
      PMA_USER: user     # Опционально, можно оставить пустым и вводить при входе
      PMA_PASSWORD: password
    depends_on:
      - db_test
    profiles:
      - default
      - test
volumes:
  manticore_data: