version: '3'

services:
  php:
    build: .
    ports:
      - "${PHP_PORT}:9000"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
      - manticore
    environment:
      - DATABASE_URL=mysql://user:password@db:3306/my_database

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./docker/mysql/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - "${MYSQL_PORT}:3306"

  manticore:
    image: manticoresearch/manticore
    ports:
      - "${MANTICORE_PORT}:9306"
      - "9308:9308"
    volumes:
      - ./manticore.conf:/etc/manticoresearch/manticore.conf

  nginx:
    image: nginx:latest
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    depends_on:
      - php

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"        # Порт, на котором будет доступен phpMyAdmin на вашем хосте
    environment:
      PMA_HOST: db       # Имя сервиса базы данных (MySQL)
      PMA_USER: user     # Опционально, можно оставить пустым и вводить при входе
      PMA_PASSWORD: password
    depends_on:
      - db
