<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXI7y9DC\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXI7y9DC/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXI7y9DC.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXI7y9DC\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXI7y9DC\App_KernelDevDebugContainer([
    'container.build_hash' => 'XI7y9DC',
    'container.build_id' => '6c1b048a',
    'container.build_time' => 1747645168,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXI7y9DC');
