<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBebPv5y\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBebPv5y/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBebPv5y.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBebPv5y\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBebPv5y\App_KernelDevDebugContainer([
    'container.build_hash' => 'BebPv5y',
    'container.build_id' => '64910f75',
    'container.build_time' => 1746802614,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBebPv5y');
